[project]
name = "nwws2mqtt"
version = "0.1.0"
description = "Provides a gateway from NWWS OI feed to MQTT server"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "jsonpickle>=4.1.0",
    "loguru>=0.7.3",
    "psycopg[binary]>=3.2.9",
    "pyiem>=1.23.0",
    "python-dotenv>=1.1.0",
    "twisted[tls]>=24.11.0",
]

[tool.ruff]
target-version = "py313"
line-length = 132
extend-exclude = [
    ".git",
    ".mypy_cache",
    ".ruff_cache",
    ".venv",
    "__pycache__",
    "build",
    "dist",
]

[tool.ruff.lint]
select = [
    "E",    # pycodestyle errors
    "W",    # pycodestyle warnings
    "F",    # pyflakes
    "I",    # isort
    "B",    # flake8-bugbear
    "C4",   # flake8-comprehensions
    "UP",   # pyupgrade
    "ARG",  # flake8-unused-arguments
    "C90",  # mccabe complexity
    "T20",  # flake8-print
    "SIM",  # flake8-simplify
    "TCH",  # flake8-type-checking
    "PTH",  # flake8-use-pathlib
    "ERA",  # eradicate
    "PL",   # pylint
    "TRY",  # tryceratops
    "RUF",  # ruff-specific rules
]
ignore = [
    "E501",   # line too long (handled by formatter)
    "TRY003", # avoid specifying long messages outside exception class
    "PLR0913", # too many arguments
    "PLR2004", # magic value used in comparison
]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"

[tool.pyright]
include = ["."]
exclude = [
    "**/__pycache__",
    ".git",
    ".mypy_cache",
    ".ruff_cache",
    ".venv",
    "build",
    "dist",
]
pythonVersion = "3.13"
pythonPlatform = "All"
typeCheckingMode = "off"
