"""
This type stub file was generated by pyright.
"""

import os

"""A utility to load matplotlib and set the backend to AGG

Example:
   from pyiem.plot.use_agg import plt
"""
if "TEST_DATA_DIR" not in os.environ:
    ...
__all__ = ["plt"]
