"""
This type stub file was generated by pyright.
"""

import os
from importlib.metadata import PackageNotFoundError, version

"""Python Utilities developed for/by Iowa Environmental Mesonet

Python is an important part of the Iowa Environmental Mesonet (IEM).  This
package is used by many parts of the IEM codebase and hopefully somewhat
useful to others!?!?
"""
__version__ = ...
pkgdir = ...
if not pkgdir.endswith("site-packages"):
    ...
