"""
This type stub file was generated by pyright.
"""

"""Geometry utility functions."""
def rhs_split(poly, splitter): # -> Polygon | BaseGeometry | None:
    """Provide the Right Hand Side Polygon associated with a split operation.

    Args:
      poly (shapely.geometry.Polygon): polygon to split.
      splitter (shapely.geometry.LineString): linestring to spliy by.

    Returns:
      shapely.geometry.Polygon
    """
    ...

