"""
This type stub file was generated by pyright.
"""

"""Network Table."""
class Table:
    """Our class"""
    def __init__(self, network, cursor=..., only_online=...) -> None:
        """A class representing a network(s) of IEM metadata

        Args:
          network (str or list): A network identifier used by the IEM, this can
            be either a string or a list of strings.
          cursor (dbcursor,optional): A database cursor to use for the query
          only_online (bool,otional): Should the listing of stations include
            only those that are currently flagged as online.
        """
        ...
    
    def get_threading_id(self, sid, valid) -> str:
        """Return a station identifier (not iemid) based on threading.

        Lookup what the threaded station identifier is based on this given
        timestamp/date.

        Args:
          sid (str): station identifier to check threading for.
          valid (datetime.date): lookup for comparison.
        """
        ...
    
    def get_id_by_key(self, key, value) -> str:
        """Find a station id by a given attribute = value.

        Args:
          key (str): attribute to lookup.
          value (mixed): value to compare against

        Returns:
          station_id
        """
        ...
    


