"""
This type stub file was generated by pyright.
"""

from datetime import datetime

"""A class representing an observation stored in the IEM database"""
SUMMARY_COLS = ...
def get_summary_table(valid): # -> str:
    """Optimize the summary table we potentially use.

    Args:
      valid (datetime with time zone): Datetime

    Returns:
      str table to query
    """
    ...

def bounded(val, floor, ceiling): # -> float | None:
    """Make sure this is not NaN and between some value."""
    ...

def summary_update(txn, data):
    """Updates the summary table and returns affected rows.

    Args:
      txn (psycopg.transaction)
      data (dict)

    Returns:
      int: affected rows count
    """
    ...

class Observation:
    """my observation object"""
    def __init__(self, station: str = ..., network: str = ..., valid: datetime = ..., iemid: int = ..., tzname: str = ...) -> None:
        """
        Constructor for the Observation.  Note you need to provide either
        a iemid + tzname or a station + network.

        Args:
          station (str): Station identifier
          network (str): Network identifier
          valid (datetime): Datetime object with tzinfo set or date.
          iemid (int): IEM internal identifier
          tzname (str): time zone string
        """
        ...
    
    def load(self, txn): # -> bool:
        """
        Load the current observation for this site and time
        """
        ...
    
    def calc(self): # -> None:
        """Compute things not usually computed"""
        ...
    
    def compute_iemid(self, txn): # -> bool:
        """Load in what our metadata is to save future queries"""
        ...
    
    def save(self, txn, force_current_log=..., skip_current=...): # -> bool:
        """
        Save this observation to the database via a psycopg transaction
        @param txn is a psycopg transaction
        @param force_current_log boolean - make sure this observation goes to
        the current_log table in the case that it is old, this allows
        reprocessing by the METAR ingestor et al
        @param skip_current boolean - optionally skip updating the current
        table.  This is useful for partial obs
        @return: boolean if this updated one row each
        """
        ...
    


