"""
This type stub file was generated by pyright.
"""

from datetime import datetime
from typing import Optional

"""Very light weight WMO header parser."""
TIME_FMT = ...
TIME_RE = ...
TIME_UTC_RE = ...
TIME_EXT_RE = ...
TIME_RE_ANYWHERE = ...
TIME_STARTS_LINE = ...
WMO_RE = ...
KNOWN_BAD_TTAAII = ...
def date_tokens2datetime(tokens): # -> tuple[Any, ZoneInfo, datetime]:
    """Convert tokens from MND regex to a valid time, if possible.

    Returns:
      z (str): 3-4 char timezone string
      tz (datetime.timezone): of this product
      utcvalid (datetimetz): of this product
    """
    ...

class WMOProduct:
    """Base class for Products with a WMO Header."""
    def __init__(self, text, utcnow: Optional[datetime] = ...) -> None:
        """Constructor."""
        ...
    
    def parse_wmo(self): # -> None:
        """Parse things related to the WMO header"""
        ...
    


