"""
This type stub file was generated by pyright.
"""

from typing import Optional, Union
from pyiem.nws.ugc import UGCProvider

"""A generalized parser frontend."""
def parser(text, utcnow=..., ugc_provider: Optional[Union[UGCProvider, dict]] = ..., nwsli_provider=...): # -> SpaceWxProduct | TextProduct | HWOProduct | NHCProduct | SPSProduct | CLIProduct | ERO | LSRProduct | MCDProduct | SAWProduct | SELProduct | SPCPTS | TAFProduct | WWPProduct:
    """Omnibus parser of NWS Text Data

    This is intended to be a catch-all parser of text data.  As it currently
    stands, it does not correctly hand products off to the correct
    sub-processor, but some day it will!

    Args:
      text (str): The actual product text, this can have the <cntr>-a
        character to start the string.
      utcnow (datetime, optional): What is the current time, this is useful
        for when ingesting old data.  Many times, the product does not contain
        enough information to assign a current valid timestamp to it.  So we
        need to know the current timestamp to do the relative computation.
      ugc_provider (UGCProvider, optional): Provides UGC information for
        product parsing.
      nwsli_provider (dict, optional): Provides NWS Location Identifiers to
        allow lookup of geographic information for station identifiers.

    Returns:
      TextProduct: A TextProduct instance

    """
    ...

