"""
This type stub file was generated by pyright.
"""

"""Off-loaded private stuff from `vtec.py`."""
DEFAULT_EXPIRE_DELTA = ...
def which_year(txn, prod, segment, vtec) -> int:
    """Figure out which table we should work against"""
    ...

def check_dup_ps(segment): # -> bool:
    """Does this TextProductSegment have duplicated VTEC

    NWS AWIPS Developer asked that alerts be made when a VTEC segment has a
    phenomena and significance that are reused. In practice, this error is
    in the case of having the same phenomena.significance overlap in time. The
    combination of the same pheom.sig for events happening now and in the
    future is OK and common

    Returns:
      bool
    """
    ...

def do_sql_hvtec(txn, segment): # -> None:
    """Process the HVTEC in this product"""
    ...

def list_rows(txn, table, vtec): # -> str:
    """Return a simple listing of what exists in the database"""
    ...

