"""
This type stub file was generated by pyright.
"""

from pyiem.nws.product import TextProduct
from pyiem.nws.vtec import VTEC

"""Consolidate VTEC to jabber logic."""
def build_channels(prod: TextProduct, segment, vtec: VTEC) -> list:
    """Build a list of channels for the given segment/vtec."""
    ...

def build_df(prod): # -> DataFrame:
    """Build a dataframe for the given product."""
    ...

