"""
This type stub file was generated by pyright.
"""

from pyiem.nws.product import TextProduct

"""Parser for the CF6 Product."""
MONTH_RE = ...
MONTH_RE_NUM = ...
YEAR_RE = ...
COL_WIDTHS = ...
COL_NAMES = ...
class CF6Product(TextProduct):
    """
    Represents a CF6 Product
    """
    def __init__(self, text, utcnow=..., ugc_provider=..., nwsli_provider=...) -> None:
        """constructor"""
        ...
    
    def parser(self): # -> None:
        """Do the parsing we need to do!"""
        ...
    
    def sql(self, cursor): # -> None:
        """Send the data to the database."""
        ...
    


def parser(text, utcnow=..., ugc_provider=..., nwsli_provider=...): # -> CF6Product:
    """Provide back CF6 objects based on the parsing of this text"""
    ...

