"""
This type stub file was generated by pyright.
"""

from pyiem.wmo import WMOProduct

"""Parser of the Daily Summary Message (DSM)."""
PARSER_RE = ...
def process(text): # -> DSMProduct | None:
    """Emit DSMProduct object for what we can parse."""
    ...

def compute_time(date, timestamp): # -> datetime | None:
    """Make a valid timestamp."""
    ...

class DSMProduct:
    """Represents a single DSM."""
    def __init__(self, groupdict) -> None:
        """Contructor."""
        ...
    
    def tzlocalize(self, tzinfo): # -> None:
        """Localize the timestamps, tricky."""
        ...
    
    def compute_times(self, utcnow): # -> None:
        """Figure out when this DSM is valid for."""
        ...
    
    def sql(self, txn, product_id: str = ...): # -> Literal[False]:
        """Persist to database given the transaction object."""
        ...
    


class DSMCollective(WMOProduct):
    """A collective representing a NOAAPort Text Product with many DSMs."""
    def __init__(self, text, utcnow=..., ugc_provider=..., nwsli_provider=...) -> None:
        """constructor"""
        ...
    
    def tzlocalize(self, tzprovider): # -> None:
        """Localize our currently stored timestamps."""
        ...
    
    def sql(self, txn) -> list[bool]:
        """Do databasing."""
        ...
    


def parser(text, utcnow=..., ugc_provider=..., nwsli_provider=...): # -> DSMCollective:
    """Provide back DSM objects based on the parsing of this text"""
    ...

