"""
This type stub file was generated by pyright.
"""

from pyiem.nws.product import TextProduct

"""Parser for the FD (Temp Wind Aloft Forecasts)."""
BASED_ON_RE = ...
VALID_RE = ...
def parse_encoding(text): # -> tuple[float, float, float] | tuple[int, int, int | float]:
    """Convert the encoded text into drct, sknt, tmpc."""
    ...

def compute_time(valid, tokens):
    """Figure out the timestamp of interest here."""
    ...

def make4(station, afos): # -> str:
    """Make this 3 character station, 4!"""
    ...

class FDProduct(TextProduct):
    """
    Represents a FD Product
    """
    def __init__(self, text, utcnow=..., ugc_provider=..., nwsli_provider=...) -> None:
        """constructor"""
        ...
    
    def parser(self): # -> None:
        """Do the parsing we need to do!"""
        ...
    
    def sql(self, cursor): # -> None:
        """Send the data to the database."""
        ...
    


def parser(text, utcnow=..., ugc_provider=..., nwsli_provider=...): # -> FDProduct:
    """Provide back FD objects based on the parsing of this text"""
    ...

