"""
This type stub file was generated by pyright.
"""

from pyiem.nws.product import TextProduct

"""Parsing of Flash Flood Guidances

NWS Discontinued 30 Sep 2018
https://www.weather.gov/media/notification/pdfs/pns18-13disc_county_ffg.pdf
"""
SHEFRE = ...
DATARE = ...
def safe(val): # -> float | None:
    """Safe conversion to float"""
    ...

class FFGProduct(TextProduct):
    """Class representing a FFG Product"""
    def __init__(self, text, utcnow=...) -> None:
        """Constructor

        Args:
          text (str): text to parse
        """
        ...
    
    def do_parsing(self): # -> None:
        """Process this file and save data"""
        ...
    
    def sql(self, txn): # -> None:
        """Do the necessary database work

        Args:
          (psycopg.transaction): a database transaction
        """
        ...
    


def parser(text, utcnow=...): # -> FFGProduct:
    """parser of raw SPC SAW Text

    Args:
      text (str): the raw text to parse
      utcnow (datetime): the current datetime with timezone set!

    Returns:
      SAWProduct instance
    """
    ...

