"""
This type stub file was generated by pyright.
"""

from pyiem.nws.product import TextProduct

"""Aviation Weather Center Graphical-AIRMET G-AIRMET.

Break-up the XML G-AIRMET into atomic pieces.
"""
GMET = ...
NS = ...
def parseUTC(s): # -> datetime:
    """Parse an ISO-ish string into UTC timestamp"""
    ...

def prettify(elem): # -> str:
    """Return a pretty-printed XML string for the Element."""
    ...

def process_airmet(prod, airmet): # -> None:
    """Process an AIRMET element"""
    ...

class GAIRMET(TextProduct):
    """Class for parsing the G-AIRMET product"""
    def __init__(self, text, utcnow=..., ugc_provider=..., nwsli_provider=...) -> None:
        """constructor"""
        ...
    
    def sql(self, cursor): # -> None:
        """Persist this information to the database"""
        ...
    
    def parsing(self): # -> None:
        """Attempt to parse out what we have found"""
        ...
    


def parser(buf, utcnow=..., ugc_provider=..., nwsli_provider=...): # -> GAIRMET:
    """Parse a G-AIRMET product

    Args:
      buf (str): What we want to parse
    """
    ...

