"""
This type stub file was generated by pyright.
"""

from pyiem.nws.product import TextProduct

"""Hazardous Weather Outlook."""
class HWOProduct(TextProduct):
    """
    Represents a HWO
    """
    def get_channels(self): # -> list[Any | str | None]:
        """overridden TextProduct#get_channels"""
        ...
    


def parser(text, utcnow=..., ugc_provider=..., nwsli_provider=...): # -> HWOProduct:
    """Helper function"""
    ...

