"""
This type stub file was generated by pyright.
"""

from pyiem.nws.product import TextProduct, TextProductException

"""NWS Local Storm Report (LSR) Parsing."""
FUTURE_THRESHOLD = ...
SPLITTER = ...
class LSRProductException(TextProductException):
    """Something we can raise when bad things happen!"""
    ...


class LSRProduct(TextProduct):
    """Represents a text product of the LSR variety"""
    def __init__(self, text, utcnow=..., ugc_provider=..., nwsli_provider=...) -> None:
        """constructor"""
        ...
    
    def get_temporal_domain(self): # -> tuple[None, None] | tuple[Any, Any]:
        """Return the min and max timestamps of lsrs"""
        ...
    
    def is_summary(self):
        """Returns is this LSR is a summary or not"""
        ...
    
    def get_url(self, baseuri): # -> str:
        """Get the URL of this product"""
        ...
    
    def get_jabbers(self, uri, _uri2=...): # -> list[Any]:
        """return a text and html variant for Jabber stuff"""
        ...
    


def parse_lsr(prod, text): # -> LSR | None:
    """Emit a LSR object based on this text!
    0914 PM     HAIL             SHAW                    33.60N 90.77W
    04/29/2005  1.00 INCH        BOLIVAR            MS   EMERGENCY MNGR
    """
    ...

def parser(text, utcnow=..., ugc_provider=..., nwsli_provider=...): # -> LSRProduct:
    """Helper function that actually converts the raw text and emits an
    LSRProduct instance or returns an exception"""
    ...

