"""
This type stub file was generated by pyright.
"""

from pyiem.wmo import WMOProduct

"""
Supports parsing of Textual Model Output Statistics files
"""
REMAP_VARS = ...
def section_parser(sect): # -> dict[str, Any]:
    """Parse this section of text"""
    ...

def make_null(val): # -> None:
    """Hmmm, perhaps we should set 999 as null too?"""
    ...

class MOSProduct(WMOProduct):
    """
    Represents a Model Output Statistics file
    """
    def __init__(self, text, utcnow=..., ugc_provider=..., nwsli_provider=...) -> None:
        """constructor"""
        ...
    
    def sql(self, txn): # -> int:
        """Persist our data to the database

        Args:
          txn: Database cursor

        Returns:
          int number of inserts made to the database
        """
        ...
    
    def parse_data(self): # -> None:
        """Parse out our data!"""
        ...
    


def parser(text, utcnow=..., ugc_provider=..., nwsli_provider=...): # -> MOSProduct:
    """Helper function"""
    ...

