"""
This type stub file was generated by pyright.
"""

from pyiem.nws.product import TextProduct

"""Handle some of the fun things that come from the Hurricane Center"""
TITLE = ...
class NHCProduct(TextProduct):
    """
    Represents a NHC
    """
    def get_jabbers(self, uri, _uri2=...): # -> list[Any] | list[list[str | dict[str, str]]]:
        """Get the jabber variant of this message"""
        ...
    


def parser(text, utcnow=..., ugc_provider=..., nwsli_provider=...): # -> NHCProduct:
    """Helper function"""
    ...

