"""
This type stub file was generated by pyright.
"""

"""
http://www.unidata.ucar.edu/data/lightning/nldn.html
"""
class NLDNProduct:
    """Simple class representing obs found in a NLDNProduct."""
    def __init__(self) -> None:
        """Constructor."""
        ...
    
    def sql(self, cursor): # -> None:
        """Persist data to the database"""
        ...
    


def parser(buf): # -> NLDNProduct:
    """NLDN (unencrypted product)"""
    ...

