"""
This type stub file was generated by pyright.
"""

from pyiem.nws.product import TextProduct

"""Parsing NESDIS Satellite Cloud Product (SCP)."""
SCP = ...
LINEFMT = ...
class SCPProduct(TextProduct):
    """Class representing a SCP Product"""
    def __init__(self, text, utcnow=...) -> None:
        """Constructor

        Args:
          text (str): text to parse
        """
        ...
    
    def sql(self, txn): # -> int:
        """Do the necessary database work

        Args:
          (psycopg.transaction): a database transaction
        """
        ...
    


def parser(text, utcnow=...): # -> SCPProduct:
    """parser of raw SCP Text.

    Args:
      text (str): the raw text to parse
      utcnow (datetime): the current datetime with timezone set!

    Returns:
      SCPProduct instance
    """
    ...

