"""
This type stub file was generated by pyright.
"""

from pyiem.nws.product import TextProduct

"""Parsing of Storm Prediction Center SEL Product."""
WATCH_RE = ...
class SELProduct(TextProduct):
    """Class representing a SEL Product"""
    def __init__(self, text, utcnow=...) -> None:
        """Constructor

        Args:
          text (str): text to parse
        """
        ...
    
    def is_test(self): # -> Literal[True]:
        """Is this a test product?"""
        ...
    
    def sql(self, txn): # -> None:
        """Do the necessary database work

        Args:
          (psycopg.transaction): a database transaction
        """
        ...
    


def parser(text, utcnow=..., _ugc_provider=..., _nwsli_provider=...): # -> SELProduct:
    """Parse SPC SEL Product.

    Args:
      text (str): the raw text to parse
      utcnow (datetime): the current datetime with timezone set!

    Returns:
      WWPProduct instance
    """
    ...

