"""
This type stub file was generated by pyright.
"""

from pyiem.nws.product import TextProduct

"""Space Weather Center processor"""
class SpaceWxProduct(TextProduct):
    """Class for parsing and representing Space Wx Products"""
    def __init__(self, text, utcnow=..., ugc_provider=..., nwsli_provider=...) -> None:
        """constructor"""
        ...
    
    def get_jabbers(self, uri, _uri2=...): # -> list[tuple[str, str, dict[str, str]]]:
        """Custom Implementation of the TextProduct#get_jabbers"""
        ...
    


def parser(buf, utcnow=..., ugc_provider=..., nwsli_provider=...): # -> SpaceWxProduct:
    """A parser implementation"""
    ...

