"""
This type stub file was generated by pyright.
"""

from pyiem.nws.product import TextProduct

"""Special Weather Statement"""
SPECIAL_WX_STATEMENT = ...
TILL = ...
def dedup_headline(headline, ugcs, counties, expire): # -> tuple[Any | Literal[''], Any | Literal['']]:
    """Try to not be redundant

    Args:
      headline (str): our current headline
      ugcs (list(ugc)): list of ugcs this SPS is for
      counties (str): our current parsed string of counties
      expire (str): our current parsed expiration string

    Returns:
       (str): our new counties, which has been deduped
       (str): our new expire, which has been deduped
    """
    ...

class SPSProduct(TextProduct):
    """A Special Weather Statement"""
    def sql(self, txn): # -> None:
        """Do database save in the case of a polygon"""
        ...
    
    def get_jabbers(self, uri, _uri2=...): # -> list[Any]:
        """return the standard [[text, html, xtra], ] for jabber"""
        ...
    


def parser(text, utcnow=..., ugc_provider=..., nwsli_provider=...): # -> SPSProduct:
    """The SPS Parser"""
    ...

