"""
This type stub file was generated by pyright.
"""

from pyiem.nws.product import TextProduct

"""TAF Parsing"""
TEMPO_TIME = ...
STID_VALID = ...
WIND_RE = ...
VIS_RE = ...
WX_RE = ...
CLOUD_RE = ...
SHEAR_RE = ...
def add_forecast_info(fx, text): # -> None:
    """Common things."""
    ...

def make_tempo(prod, text): # -> TAFForecast | None:
    """Parse a tempo group."""
    ...

def make_forecast(prod, text): # -> TAFForecast:
    """Build a TAFForecast data model."""
    ...

def ddhhmi2valid(prod, text):
    """Figure out what valid time this is."""
    ...

def parse_prod(prod): # -> TAFReport:
    """Generate a data object from this product."""
    ...

class TAFProduct(TextProduct):
    """
    Represents a TAF
    """
    def __init__(self, text, utcnow=..., ugc_provider=..., nwsli_provider=...) -> None:
        """constructor"""
        ...
    
    def get_channels(self): # -> list[str]:
        """Return a list of channels"""
        ...
    
    def sql(self, txn): # -> None:
        """Persist to the database."""
        ...
    
    def get_jabbers(self, uri, _uri2=...): # -> list[Any]:
        """Get the jabber variant of this message"""
        ...
    


def parser(text, utcnow=..., ugc_provider=..., nwsli_provider=...): # -> TAFProduct:
    """Helper function"""
    ...

