"""
This type stub file was generated by pyright.
"""

from pyiem.nws.product import TextProduct

"""WPC's XTEUS Nationwide High/Low."""
ISO = ...
class XTEUSProduct(TextProduct):
    """A Special Weather Statement"""
    def __init__(self, text, utcnow=..., ugc_provider=..., nwsli_provider=...) -> None:
        """constructor"""
        ...
    
    def sql(self, cursor): # -> None:
        """Do database insert logic."""
        ...
    


def parser(text, utcnow=..., ugc_provider=..., nwsli_provider=...): # -> XTEUSProduct:
    """The XTEUS Parser"""
    ...

