"""
This type stub file was generated by pyright.
"""

"""Process HVTEC encoding."""
_re = ...
HVTEC_RECORD = ...
HVTEC_CAUSE = ...
HVTEC_SEVERITY = ...
def parse(text, nwsli_provider=..., tp=...): # -> list[Any]:
    """Return list of HVTEC entries found within text.

    Args:
      text (str): String to look for HVTEC tokens within.
      nwsli_provider (dict): Provider of metadata.
      tp (TextProduct): TextProduct instance used for provider and warnings.

    Returns:
      list(HVTEC)
    """
    ...

def contime(s): # -> datetime | None:
    """Process a string into time."""
    ...

class HVTEC:
    """Hydro VTEC."""
    def __init__(self, tokens, nwsli_provider=...) -> None:
        """Constructor"""
        ...
    
    def __str__(self) -> str:
        """string representation of this HVTEC"""
        ...
    
    def __repr__(self) -> str:
        """Return a representation."""
        ...
    


