"""
This type stub file was generated by pyright.
"""

"""National Weather Service Location Idenitifiers (NWSLI)

A class to store metadata associated with a NWSLI entry.
"""
class NWSLI:
    """National Weather Service Location Idenitifiers (NWSLI)"""
    def __init__(self, identifier, name=..., wfos=..., lon=..., lat=...) -> None:
        """Constructor

        Args:
          identifier(str): The string identifier for this NWSLI
          name(str, optional): The free-form text name of this location
          wfo(list, optional): The wfo(s) associated with this NWSLI
          lon(float, optional): The longitude in decimal degrees
          lat(float, optional): The latitude in decimal degress
        """
        ...
    
    def get_name(self): # -> str:
        """Return the name of this NWSLI, uses `self.id` if name is unset

        Returns:
            str: the name of this site
        """
        ...
    
    def __getitem__(self, key): # -> float | Any:
        """Overload __getitem__ to return the value of the attribute"""
        ...
    


