"""
This type stub file was generated by pyright.
"""

from typing import Tuple

"""Stubs for the C geohash module."""
def encode(latitude: float, longitude: float, precision: int) -> str:
    ...

def encode_strictly(latitude: float, longitude: float, precision: int) -> str:
    ...

def decode(geohash: str) -> Tuple[float, float]:
    ...

def decode_exactly(geohash: str) -> Tuple[float, float, float, float]:
    ...

def get_base32() -> str:
    ...

