"""
This type stub file was generated by pyright.
"""

from types import ModuleType
from typing import Any, Callable, Sequence, Tuple

"""
Low level functions and classes related to callables.

The AUTO_TOPIC
is the "marker" to use in callables to indicate that when a message
is sent to those callables, the topic object for that message should be
added to the data sent via the call arguments. See the docs in
CallArgsInfo regarding its autoTopicArgName data member.

:copyright: Copyright since 2006 by Oliver Schoenborn, all rights reserved.
:license: BSD, see LICENSE_BSD_Simple.txt for details.

"""
class AUTO_TOPIC:
    ...


UserListener = Callable[..., Any]
def getModule(obj: Any) -> ModuleType:
    """
    Get the module in which an object was defined.
    :param obj: the object for which to get module
    :return: the module object, or the string '__main__' if no module defined for obj
        (which usually indicates either a builtin, or a definition within main script).
    """
    ...

def getID(callable_obj: UserListener) -> Tuple[str, ModuleType]:
    """
    Get "ID" of a callable, in the form of its name and module in which it is defined
    E.g. getID(Foo.bar) returns ('Foo.bar', 'a.b') if Foo.bar was defined in module a.b.
    :param callable_obj: a callable, ie function, bound method or callable instance
    """
    ...

def getRawFunction(callable_obj: UserListener) -> Tuple[Callable]:
    """
    Get raw function information about a callable.
    :param callable_obj: any object that can be called
    :return: function corresponding to callable, and offset is 0 or 1 to
        indicate whether the function's first argument is 'self' (1) or not (0)
    :raise ValueError: if callable_obj is not of a recognized type (function, method or object with __call__ method).
    """
    ...

class ListenerMismatchError(ValueError):
    """
    Raised when an attempt is made to subscribe a listener to
    a topic, but listener does not satisfy the topic's message data
    specification (MDS). This specification is inferred from the first
    listener subscribed to a topic, or from an imported topic tree
    specification (see pub.addTopicDefnProvider()).
    """
    def __init__(self, msg: str, listener: UserListener, *args) -> None:
        ...
    
    def __str__(self) -> str:
        ...
    


class CallArgsInfo:
    """
    Represent the "signature" of a listener of topic messages: which arguments are
    required vs optional.
    """
    def __init__(self, func: UserListener, ignoreArgs: Sequence[str] = ...) -> None:
        """
        :param func: the callable for which to get paramaters info
        :param ignoreArgs: do not include the given names in the get*Args() return values

        After construction,
        - self.acceptsAllKwargs = True if the listener has a **kwargs arg
        - self.autoTopicArgName will be the name of argument in which to put the Topic
          object for which pubsub message is sent, or None if auto off. This is identified
          by a parameter that has a default value of AUTO_TOPIC.

        For instance,
        - listener(self, arg1, arg2=AUTO_TOPIC, arg3=None) will have self.allParams = (arg1, arg2, arg3),
            self.numRequired=1, and self.autoTopicArgName = 'arg2', whereas
        - listener(self, arg1, arg3=None) will have self.allParams = (arg1, arg3), self.numRequired=1, and
            self.autoTopicArgName = None.
        """
        ...
    
    def getAllArgs(self) -> Tuple[str]:
        """
        Return a tuple of names indicating the complete set of message data
        (keyword args) that can be given to this listener
        """
        ...
    
    def getOptionalArgs(self) -> Tuple[str]:
        """
        Return a tuple of names indicating which message data (keyword args)
        are optional when this listener is called.
        """
        ...
    
    def getRequiredArgs(self) -> Tuple[str]:
        """
        Return a tuple of names indicating which message data (keyword args)
        are required when this listener is called.
        """
        ...
    


def getArgs(callable_obj: UserListener, ignoreArgs: Sequence[str] = ...) -> CallArgsInfo:
    """
    Get the call parameters of a callable to be used as listener.
    :param callable_obj: the callable for which to get call parameters
    :param ignoreArgs: optional list of names of parameters of callable_obj that should not be in the returned object
    :return: an instance of CallArgsInfo for the given callable_obj
    :raise ListenerMismatchError: if callable_obj is not a callable, or ignoreArgs has an item that is not a call
        param of callable
    """
    ...

