"""
This type stub file was generated by pyright.
"""

from weakref import WeakMethod, ref as WeakRef
from typing import Callable, Union

"""
This module hides the source of implementation of weak ref to a method: for Python 3.4, it is
Python's weakref module; for earlier Python, it is the weakrefmethod module from PyPI.
Prior to pypubsub 4.0, WeakMethod was a custom class that adhered to the WeakRef API.

Use the getWeakRef(object) module function to create the
proper type of weak reference (weakref.WeakRef or WeakMethod) for given object.

:copyright: Copyright since 2006 by Oliver Schoenborn, all rights reserved.
:license: BSD, see LICENSE_BSD_Simple.txt for details.
"""
WeakObjOrMethod = Union[WeakMethod, WeakRef]
DeadRefObserver = Callable[[WeakObjOrMethod], None]
def getWeakRef(obj, notifyDead: DeadRefObserver = ...): # -> ReferenceType[MethodType | Any] | WeakMethod[MethodType | Any]:
    """
    Get a weak reference to obj. If obj is a bound method, a WeakMethod
    object, that behaves like a WeakRef, is returned; if it is
    anything else a WeakRef is returned. If obj is an unbound method,
    a ValueError will be raised.
    """
    ...

