"""
This type stub file was generated by pyright.
"""

from datetime import datetime
from pydantic import BaseModel
from shapely.geometry import Polygon

"""Data Model for CWA."""
class CWAModel(BaseModel):
    """A Center Weather Advisory."""
    model_config = ...
    center: str
    expire: datetime
    geom: Polygon
    issue: datetime
    is_corrected: bool
    narrative: str
    num: int


