"""
This type stub file was generated by pyright.
"""

from datetime import datetime
from typing import List, Optional
from pydantic import BaseModel
from shapely.geometry import MultiLineString, Polygon

"""Data Model for GAIRMET."""
class AIRMETRecord(BaseModel):
    """A single AIRMET Record."""
    model_config = ...
    gml_id: str
    label: str
    status: str
    hazard_type: str
    valid_at: datetime
    weather_conditions: List[str]
    geom: Polygon


class FreezingLevelRecord(BaseModel):
    """A single FreezingLevel Record."""
    model_config = ...
    gml_id: str
    valid_at: datetime
    geom: MultiLineString
    level: Optional[int] = ...
    lower_level: int
    upper_level: int


class GAIRMETModel(BaseModel):
    """A G-AIRMET."""
    valid_from: datetime
    valid_to: datetime
    issuetime: datetime
    airmets: List[AIRMETRecord] = ...
    freezing_levels: List[FreezingLevelRecord] = ...


