"""
This type stub file was generated by pyright.
"""

from pydantic import BaseModel

"""Pydantic data model for SPC Watch (SEL)."""
class SELModel(BaseModel):
    """SPC Watch Probability."""
    typ: str = ...
    num: int = ...


