"""
This type stub file was generated by pyright.
"""

from typing import Dict, Final, Literal
from pygeohash.types import Direction

"""Geohash neighbor calculation functionality.

This module provides functionality for calculating adjacent geohashes
in different directions (right, left, top, bottom).
"""
logger = ...
NEIGHBORS: Final[Dict[Direction, Dict[Literal["even", "odd"], str]]] = ...
BORDERS: Final[Dict[Direction, Dict[Literal["even", "odd"], str]]] = ...
def get_adjacent(geohash: str, direction: Direction) -> str:
    """Calculate the adjacent geohash in the specified direction.

    Args:
        geohash (str): The input geohash string.
        direction (Direction): The direction to find the adjacent geohash.
        Must be one of: "right", "left", "top", "bottom".

    Returns:
        str: The adjacent geohash in the specified direction.

    Raises:
        ValueError: If the geohash length is 0 (possible when close to poles).

    Example:
        >>> get_adjacent("u4pruyd", "top")
        'u4pruyf'
    """
    ...

