"""
This type stub file was generated by pyright.
"""

"""
Pubsub package initialization.

:copyright: Copyright since 2006 by Oliver Schoenborn, all rights reserved.
:license: BSD, see LICENSE_BSD_Simple.txt for details.
"""
__version__ = ...
__all__ = ['pub', 'utils', '__version__']
