"""
This type stub file was generated by pyright.
"""

from typing import List
from .core import Publisher, Topic, TopicManager

"""
This is the main entry-point to pubsub's core functionality. The :mod:`~pubsub.pub`
module supports:

* messaging: publishing and receiving messages of a given topic
* tracing: tracing pubsub activity in an application
* trapping exceptions: dealing with "badly behaved" listeners (ie that leak exceptions)
* specificatio of topic tree: defining (or just documenting) the topic tree of an
  application; message data specification (MDS)

The recommended usage is ::

    from pubsub import pub

    // use pub functions:
    pub.sendMessage(...)

Note that this module creates a "default" instance of
pubsub.core.Publisher and binds several local functions to some of its methods
and those of the pubsub.core.TopicManager instance that it contains. However, an
application may create as many independent instances of Publisher as
required (for instance, one in each thread; with a custom queue to mediate
message transfer between threads).
"""
VERSION_API = ...
VERSION_SVN = ...
__all__ = ['subscribe', 'unsubscribe', 'unsubAll', 'isSubscribed', 'isValid', 'validate', 'ListenerMismatchError', 'AUTO_TOPIC', 'IListenerExcHandler', 'getListenerExcHandler', 'setListenerExcHandler', 'ExcHandlerError', 'ALL_TOPICS', 'Topic', 'topicTreeRoot', 'topicsMap', 'TopicManager', 'getDefaultTopicMgr', 'addTopicDefnProvider', 'clearTopicDefnProviders', 'getNumTopicDefnProviders', 'TOPIC_TREE_FROM_MODULE', 'TOPIC_TREE_FROM_CLASS', 'TOPIC_TREE_FROM_STRING', 'exportTopicTreeSpec', 'instantiateAllDefinedTopics' 'TopicDefnError', 'TopicNameError', 'setTopicUnspecifiedFatal', 'sendMessage', 'addNotificationHandler', 'setNotificationFlags', 'getNotificationFlags', 'clearNotificationHandlers', 'TopicTreeTraverser']
_publisher = ...
subscribe = ...
unsubscribe = ...
unsubAll = ...
sendMessage = ...
getListenerExcHandler = ...
setListenerExcHandler = ...
addNotificationHandler = ...
clearNotificationHandlers = ...
setNotificationFlags = ...
getNotificationFlags = ...
setTopicUnspecifiedFatal = ...
def getDefaultPublisher() -> Publisher:
    """
    Get the Publisher instance created by default when this module
    is imported. See the module doc for details about this instance.
    """
    ...

_topicMgr = ...
topicTreeRoot = ...
topicsMap = ...
def isValid(listener, topicName, curriedArgNames=...) -> bool:
    """
    Return true only if listener can subscribe to messages of given topic.
    If curriedArgNames can be a list of parameters of the given listener, that
    should be assumed curried (i.e. actual listener signature is signature of
    given listener minus curried args).
    """
    ...

def validate(listener, topicName, curriedArgNames=...): # -> None:
    """
    Checks if listener can subscribe to topicName. If not, raises
    ListenerMismatchError, otherwise just returns. The curriedArgNames is
    same as for isValid().
    """
    ...

def isSubscribed(listener, topicName) -> bool:
    """
    Returns true if listener has subscribed to topicName, false otherwise.
    WARNING: a false return is not a guarantee that listener won't get
    messages of topicName: it could receive messages of a subtopic of
    topicName.
    """
    ...

def getDefaultTopicMgr() -> TopicManager:
    """
    Get the TopicManager instance created by default when this
    module is imported. This function is a shortcut for
    ``pub.getDefaultPublisher().getTopicMgr()``.
    """
    ...

addTopicDefnProvider = ...
clearTopicDefnProviders = ...
getNumTopicDefnProviders = ...
def instantiateAllDefinedTopics(provider) -> List[Topic]:
    """
    Loop over all topics of given provider and "instantiate" each topic, thus
    forcing a parse of the topics documentation, message data specification (MDS),
    comparison with parent MDS, and MDS documentation. Without this function call,
    an error among any of those characteristics will manifest only if the a
    listener is registered on it.
    """
    ...

